# Generated by Django 6.0.2 on 2026-02-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_addjob_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='final_app.adminmodel'),
        ),
    ]
