# Generated by Django 6.0.2 on 2026-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_alter_addjob_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_of_jobseeker',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
