# Generated by Django 6.0.2 on 2026-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0006_detail_of_jobseeker_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_of_jobseeker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail_of_jobseeker',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail_of_jobseeker',
            name='year_of_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
